---
title: "gTrends"
author: "James Walsh"
date: "10/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library("gtrendsR")
library("spData")
library("tidyverse")
```

```{r data download}
US.inflation.trends<-head(gtrends(keyword="inflation",time="all", geo="US"))
US.inflation.trends.12m<-head(gtrends(keyword="inflation",time="today 12-m", geo="US"))
world.inflation.trends<-head(gtrends(keyword="inflation",time="all"))
world.prices.trends<-head(gtrends(keyword="prices",time="all"))
world.jobs.trends<-head(gtrends(keyword="jobs",time="all"))
world.hedgefund.trends<-head(gtrends(keyword="hedge funds",time="all"))
world.albourne.trends<-head(gtrends(keyword="Albourne",time="all"))



iot.US<-US.inflation.trends$interest_over_time
iot.albourne<-world.albourne.trends$interest_over_time
iot.prices<-world.prices.trends$interest_over_time
iot.jobs<-world.jobs.trends$interest_over_time
iot.hedgefund<-world.albourne.trends$interest_over_time

iot.US %>%
    ggplot(aes(x=date,y=hits))+
    geom_line()

iot.albourne %>%
    ggplot(aes(x=date,y=hits))+
    geom_line()

iot.prices%>%
    ggplot(aes(x=date,y=hits))+
    geom_line()

iot.jobs %>%
    ggplot(aes(x=date,y=hits))+
    geom_line()

iot.hedgefund %>%
    ggplot(aes(x=date,y=hits))+
    geom_line()



US.inflation.trends.12m$related_topics %>%
    filter(related_topics=="top")%>%
    mutate(value=factor(value,levels=rev(as.character(value))),subject=as.numeric(subject))%>%
    top_n(10,value) %>%
    ggplot(aes(x=value,y=subject,fill="red"))+
    geom_bar(stat='identity',show.legend = F)+
    coord_flip()+
    labs(title="Queries most related with 'inflation'")

ioc<-world.inflation.trends$interest_by_country

countries<-spData::world %>%
    left_join(y=ioc,by=c("name_long" = "location"),keep=T)

tm_shape(countries)+
    tm_fill("hits")

library(spData)
world_sp = as(world, "Spatial")
world_sf = st_as_sf(world_sp)


```
